version: "3.9"

services:
  app:
    build: .
    container_name: inventory_management_system
    ports:
      - "8000:8000"
    volumes:
      - .:/inventory_management_system
    environment:
      - ENV=production
    command: ["make", "run"]
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: inventory_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:


# version: "3.9"

# services:
#   db:
#     image: postgres:17
#     environment:
#       POSTGRES_USER: fastapi_user
#       POSTGRES_PASSWORD: 123456
#       POSTGRES_DB: inventory_db
#     ports:
#       - "5432:5432"

#   api:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
