version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
