"""Add check constraint for positive price

Revision ID: 6dfebb9d8078
Revises: dd26e7936962
Create Date: 2025-02-27 13:17:05.191764

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dfebb9d8078"
down_revision: Union[str, None] = "dd26e7936962"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
