"""Recreating initial migration

Revision ID: 900b30c1110e
Revises:
Create Date: 2025-02-20 05:04:13.172445

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "900b30c1110e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("min_stock", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_product_id"), ["product_id"], unique=False)

    op.create_table(
        "movement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("source_store_id", sa.String(), nullable=True),
        sa.Column("target_store_id", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movement", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_movement_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_movement_product_id"), ["product_id"], unique=False)

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_name"), ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_name"))
        batch_op.drop_index(batch_op.f("ix_products_id"))

    op.drop_table("products")
    with op.batch_alter_table("movement", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movement_product_id"))
        batch_op.drop_index(batch_op.f("ix_movement_id"))

    op.drop_table("movement")
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_product_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_id"))

    op.drop_table("inventory")
    # ### end Alembic commands ###
