"""Corrige product_id y crea movements table

Revision ID: caee85aa0b98
Revises: d6e9ac5fda34
Create Date: 2025-02-25 18:02:34.060030

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "caee85aa0b98"
down_revision: Union[str, None] = "d6e9ac5fda34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movement", schema=None) as batch_op:
        batch_op.drop_index("ix_movement_id")
        batch_op.drop_index("ix_movement_product_id")

    op.drop_table("movement")
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.drop_index("ix_inventory_product_id")

    op.drop_table("inventory")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("category", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column("category", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=True)

    op.create_table(
        "inventory",
        sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("store_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("min_stock", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="inventory_pkey"),
    )
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.create_index("ix_inventory_product_id", ["product_id"], unique=False)

    op.create_table(
        "movement",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("source_store_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("target_store_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="movement_pkey"),
    )
    with op.batch_alter_table("movement", schema=None) as batch_op:
        batch_op.create_index("ix_movement_product_id", ["product_id"], unique=False)
        batch_op.create_index("ix_movement_id", ["id"], unique=False)

    # ### end Alembic commands ###
